spring:
  application:
    name: spring-boot-mongo

  data:
    mongodb:
      #      uri: ${vcap.services.mongodb.credentials.uri:mongodb}
      uri: mongodb://localhost:27017/demodb

logging:
  level:
    org.springframework.data.mongodb.observability: DEBUG
